import os
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
)
from reportlab.lib.units import inch


def create_pdf(
    complaint_id,
    category,
    location,
    language,
    complaint,
    ai_report
):

    # -----------------------------
    # Create Reports Folder
    # -----------------------------

    reports_folder = os.path.join("data", "reports")

    os.makedirs(reports_folder, exist_ok=True)

    pdf_path = os.path.join(
        reports_folder,
        f"{complaint_id}.pdf"
    )

    # -----------------------------
    # PDF Document
    # -----------------------------

    doc = SimpleDocTemplate(pdf_path)

    styles = getSampleStyleSheet()

    title_style = styles["Heading1"]
    title_style.alignment = TA_CENTER

    heading = styles["Heading2"]

    normal = styles["BodyText"]

    story = []

    # -----------------------------
    # Title
    # -----------------------------

    story.append(
        Paragraph(
            "CIVIC INTELLIGENCE SYSTEM",
            title_style
        )
    )

    story.append(
        Paragraph(
            "AI Community Complaint Report",
            heading
        )
    )

    story.append(
        Spacer(1, 0.3 * inch)
    )

    # -----------------------------
    # Complaint Details
    # -----------------------------

    story.append(
        Paragraph(
            "<b>Complaint ID:</b> " + complaint_id,
            normal
        )
    )

    story.append(
        Paragraph(
            "<b>Category:</b> " + category,
            normal
        )
    )

    story.append(
        Paragraph(
            "<b>Location:</b> " + location,
            normal
        )
    )

    story.append(
        Paragraph(
            "<b>Language:</b> " + language,
            normal
        )
    )

    story.append(
        Spacer(1, 0.2 * inch)
    )

    # -----------------------------
    # Citizen Complaint
    # -----------------------------

    story.append(
        Paragraph(
            "Citizen Complaint",
            heading
        )
    )

    story.append(
        Paragraph(
            complaint.replace("\n", "<br/>"),
            normal
        )
    )

    story.append(
        Spacer(1, 0.3 * inch)
    )

    # -----------------------------
# AI Report
# -----------------------------

    story.append(
        Paragraph(
        "AI Decision Intelligence Report",
        heading
        )
    )

    story.append(
        Paragraph(
        f"<b>Issue Type:</b> {ai_report['issue_type']}",
        normal
        )
    )

    story.append(
        Paragraph(
        f"<b>Problem Summary:</b> {ai_report['problem_summary']}",
        normal
        )
    )

    story.append(
        Paragraph(
        f"<b>Severity:</b> {ai_report['severity']}",
        normal
        )
    )

    story.append(
        Paragraph(
        f"<b>Priority Score:</b> {ai_report['priority_score']}%",
        normal
        )
    )

    story.append(Spacer(1, 0.15 * inch))

    story.append(Paragraph("<b>Responsible Departments</b>", heading))

    for dept in ai_report["department"]:
        story.append(
            Paragraph(f"• {dept}", normal)
        )

    story.append(Spacer(1, 0.15 * inch))

    story.append(Paragraph("<b>Root Causes</b>", heading))

    for cause in ai_report["root_causes"]:
        story.append(
            Paragraph(f"• {cause}", normal)
        )

    story.append(Spacer(1, 0.15 * inch))

    story.append(Paragraph("<b>Immediate Actions</b>", heading))

    for action in ai_report["immediate_actions"]:
        story.append(
            Paragraph(f"• {action}", normal)
        )

    story.append(Spacer(1, 0.15 * inch))

    story.append(Paragraph("<b>Short-term Actions</b>", heading))

    for action in ai_report["short_term_actions"]:
        story.append(
            Paragraph(f"• {action}", normal)
        )

    story.append(Spacer(1, 0.15 * inch))

    story.append(Paragraph("<b>Long-term Actions</b>", heading))

    for action in ai_report["long_term_actions"]:
        story.append(
            Paragraph(f"• {action}", normal)
        )

    story.append(Spacer(1, 0.15 * inch))

    story.append(Paragraph("<b>Community Benefits</b>", heading))

    for benefit in ai_report["community_benefits"]:
         story.append(
            Paragraph(f"• {benefit}", normal)
        )

    story.append(
        Spacer(1, 0.3 * inch)
    )

    # -----------------------------
    # Footer
    # -----------------------------

    story.append(
        Paragraph(
            "<b>Generated by Civic Intelligence System</b>",
            normal
        )
    )

    # story.append(
    #     Paragraph(
    #         "Powered by Google Gemini AI",
    #         normal
    #     )
    # )

    # -----------------------------
    # Build PDF
    # -----------------------------

    doc.build(story)

    return pdf_path